databases:
  - name: vente-gdj-eebc-db
    databaseName: vente_gdj_eebc
    plan: free

services:
  - type: web
    name: vente-gdj-eebc
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
      python manage.py setup_users
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://vente-gdj-eebc.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: vente-gdj-eebc-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.13.0"
      - key: DEFAULT_ADMIN_USERNAME
        value: "admin"
      - key: DEFAULT_ADMIN_PASSWORD
        generateValue: true
      - key: DEFAULT_CAISSE_USERNAME
        value: "caisse"
      - key: DEFAULT_CAISSE_PASSWORD
        generateValue: true
      - key: DEFAULT_PREPARATION_USERNAME
        value: "preparation"
      - key: DEFAULT_PREPARATION_PASSWORD
        generateValue: true
