# Generated by Django 6.0.2 on 2026-03-18 20:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.PositiveIntegerField(verbose_name='N° Ticket')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token QR')),
                ('forfait', models.CharField(choices=[('individuel', 'Individuel'), ('famille', 'Famille')], max_length=20, verbose_name='Forfait')),
                ('nb_persons', models.PositiveIntegerField(default=1, verbose_name='Nb personnes')),
                ('dining_type', models.CharField(choices=[('sur_place', 'Sur place'), ('a_emporter', 'À emporter')], max_length=20, verbose_name='Type')),
                ('meat', models.CharField(max_length=100, verbose_name='Viande')),
                ('side', models.CharField(max_length=100, verbose_name='Accompagnement')),
                ('vegetable', models.CharField(blank=True, max_length=100, verbose_name='Légume')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix unitaire')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('payment_status', models.CharField(choices=[('non_paye', 'Non payé'), ('paye', 'Payé'), ('attente', 'Monnaie en attente')], default='non_paye', max_length=20, verbose_name='Paiement')),
                ('preparation_status', models.CharField(choices=[('non_lance', 'Non lancé'), ('en_preparation', 'En préparation'), ('prepare', 'Préparé'), ('recupere', 'Récupéré')], default='non_lance', max_length=20, verbose_name='Préparation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('prepared_at', models.DateTimeField(blank=True, null=True, verbose_name='Préparé le')),
                ('retrieved_at', models.DateTimeField(blank=True, null=True, verbose_name='Récupéré le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.customer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.event')),
            ],
            options={
                'verbose_name': 'Commande',
                'ordering': ['ticket_number'],
                'unique_together': {('event', 'ticket_number')},
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='core.order')),
            ],
            options={
                'verbose_name': 'Historique statut',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('caisse', 'Caisse'), ('preparation', 'Préparation / Distribution')], default='caisse', max_length=20, verbose_name='Rôle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
            },
        ),
    ]
