# Generated by Django 6.0.2 on 2026-03-19 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('preparation', 'Préparation'), ('payment', 'Paiement')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('target_role', models.CharField(choices=[('admin', 'Administrateur'), ('caisse', 'Caisse'), ('preparation', 'Préparation / Distribution')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lancé le'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['event', 'preparation_status'], name='core_order_event_i_60fe76_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['event', 'payment_status'], name='core_order_event_i_b9554f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['qr_token'], name='core_order_qr_toke_f86f85_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['ticket_number'], name='core_order_ticket__67010c_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.order'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['target_role', 'is_read'], name='core_notifi_target__41d8ad_idx'),
        ),
    ]
