# Generated by Django 6.0.2 on 2026-03-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_order_started_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(choices=[('meat', 'Viande'), ('side', 'Accompagnement'), ('vegetable', 'Légume')], max_length=20, verbose_name="Type d'option")),
                ('label', models.CharField(max_length=100, verbose_name='Libellé')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Option de menu',
                'verbose_name_plural': 'Options de menu',
                'ordering': ['option_type', 'sort_order', 'label'],
                'unique_together': {('option_type', 'label')},
            },
        ),
    ]
