# Generated by Django 5.2.12 on 2026-03-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes internes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Servi le'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_rating'], name='core_order_custome_52fd46_idx'),
        ),
    ]
